"""Generate runnable CLI wrappers and skills from API specs.

The core entry point is :func:`press`, which takes a service name and either an
OpenAPI spec (dict) or a base URL, and emits:

  * a self-contained Python CLI (``<service>_cli.py``) using only the stdlib
    (urllib) so the generated tool has no third-party dependencies, and
  * a ``SKILL.md`` describing how an agent should invoke it.

Both are written into a skills directory so Anvil's ``skill`` tool can load
them, and the CLI can be executed directly via ``bash``.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Endpoint:
    """A single API operation extracted from a spec."""

    method: str
    path: str
    operation_id: str
    summary: str = ""
    path_params: list[str] = field(default_factory=list)
    query_params: list[str] = field(default_factory=list)

    @property
    def command_name(self) -> str:
        """A CLI-friendly command name derived from the operation id."""
        name = re.sub(r"[^0-9a-zA-Z]+", "-", self.operation_id).strip("-").lower()
        return name or f"{self.method.lower()}-{self.path.strip('/').replace('/', '-') or 'root'}"


@dataclass
class PressResult:
    """The artifacts produced by a press run."""

    service: str
    base_url: str
    endpoints: list[Endpoint]
    cli_path: Path
    skill_path: Path
    cli_source: str
    skill_md: str


def _slug(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_").lower() or "service"


def parse_openapi(spec: dict) -> tuple[str, list[Endpoint]]:
    """Parse an OpenAPI/Swagger spec dict into a base URL and endpoint list."""
    base_url = ""
    servers = spec.get("servers")
    if isinstance(servers, list) and servers:
        base_url = servers[0].get("url", "")
    if not base_url:
        # Swagger 2.0 style
        host = spec.get("host", "")
        base = spec.get("basePath", "")
        schemes = spec.get("schemes") or ["https"]
        if host:
            base_url = f"{schemes[0]}://{host}{base}"

    endpoints: list[Endpoint] = []
    paths = spec.get("paths", {})
    for path, item in paths.items():
        if not isinstance(item, dict):
            continue
        for method, op in item.items():
            if method.lower() not in ("get", "post", "put", "patch", "delete"):
                continue
            if not isinstance(op, dict):
                continue
            op_id = op.get("operationId") or f"{method}_{path}"
            params = op.get("parameters", []) or []
            path_params = [p["name"] for p in params if isinstance(p, dict) and p.get("in") == "path"]
            query_params = [p["name"] for p in params if isinstance(p, dict) and p.get("in") == "query"]
            # Path-template params may not be declared explicitly.
            for tmpl in re.findall(r"\{([^}]+)\}", path):
                if tmpl not in path_params:
                    path_params.append(tmpl)
            endpoints.append(
                Endpoint(
                    method=method.upper(),
                    path=path,
                    operation_id=op_id,
                    summary=op.get("summary", "") or op.get("description", "")[:120],
                    path_params=path_params,
                    query_params=query_params,
                )
            )
    return base_url, endpoints


_CLI_HEADER = '''#!/usr/bin/env python3
"""Auto-generated Anvil Printing Press CLI for {service}.

Base URL: {base_url}
Generated by anvil.printing_press — stdlib only (no third-party deps).

Usage:
  python {filename} <command> [--param value ...]
  python {filename} --list
Auth: set the {env_token} environment variable to send a Bearer token.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.parse
import urllib.request

BASE_URL = "{base_url}".rstrip("/")
ENV_TOKEN = "{env_token}"

ENDPOINTS = {endpoints_json}


def _request(method, path, path_params, query_params):
    url = BASE_URL + path
    for key, val in path_params.items():
        url = url.replace("{{" + key + "}}", urllib.parse.quote(str(val)))
    if query_params:
        url += "?" + urllib.parse.urlencode({{k: v for k, v in query_params.items() if v is not None}})
    headers = {{"Accept": "application/json"}}
    token = os.environ.get(ENV_TOKEN)
    if token:
        headers["Authorization"] = "Bearer " + token
    data = None
    if method in ("POST", "PUT", "PATCH"):
        body = os.environ.get("PRESS_BODY")
        if body:
            data = body.encode()
            headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            raw = resp.read().decode()
            try:
                return 0, json.dumps(json.loads(raw), indent=2)
            except json.JSONDecodeError:
                return 0, raw
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode(errors="replace")
    except Exception as exc:  # noqa: BLE001
        return 1, "Error: " + str(exc)


def _parse_args(argv):
    params = {{}}
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg.startswith("--"):
            key = arg[2:]
            value = argv[i + 1] if i + 1 < len(argv) else ""
            params[key] = value
            i += 2
        else:
            i += 1
    return params


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("--list", "-l", "help", "--help"):
        print("Available commands for {service}:")
        for name, meta in ENDPOINTS.items():
            print(f"  {{name:30}} {{meta['method']:6}} {{meta['path']}}")
        return 0
    command = argv[0]
    meta = ENDPOINTS.get(command)
    if not meta:
        print("Unknown command: " + command, file=sys.stderr)
        print("Run with --list to see available commands.", file=sys.stderr)
        return 2
    supplied = _parse_args(argv[1:])
    path_params = {{k: supplied.get(k, "") for k in meta["path_params"]}}
    query_params = {{k: supplied.get(k) for k in meta["query_params"] if k in supplied}}
    code, output = _request(meta["method"], meta["path"], path_params, query_params)
    print(output)
    return 0 if code == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
'''


def generate_cli_source(service: str, base_url: str, endpoints: list[Endpoint], filename: str) -> str:
    """Render the stdlib-only CLI source for the given service/endpoints."""
    env_token = f"{_slug(service).upper()}_TOKEN"
    endpoints_map = {
        ep.command_name: {
            "method": ep.method,
            "path": ep.path,
            "summary": ep.summary,
            "path_params": ep.path_params,
            "query_params": ep.query_params,
        }
        for ep in endpoints
    }
    endpoints_json = json.dumps(endpoints_map, indent=4)
    return _CLI_HEADER.format(
        service=service,
        base_url=base_url,
        filename=filename,
        env_token=env_token,
        endpoints_json=endpoints_json,
    )


def generate_skill_md(service: str, base_url: str, endpoints: list[Endpoint], cli_filename: str) -> str:
    """Render a SKILL.md teaching the agent how to use the generated CLI."""
    env_token = f"{_slug(service).upper()}_TOKEN"
    lines = [
        f"# Skill: {service} API",
        "",
        f"Use this skill to call the **{service}** API via an auto-generated CLI.",
        "",
        f"- Base URL: `{base_url}`",
        f"- CLI: `python {cli_filename} <command> [--param value ...]`",
        f"- List commands: `python {cli_filename} --list`",
        f"- Auth: export `{env_token}` for a Bearer token. For request bodies, set `PRESS_BODY` to a JSON string.",
        "",
        "## Available commands",
        "",
        "| Command | Method | Path | Summary |",
        "|---------|--------|------|---------|",
    ]
    for ep in endpoints:
        summary = (ep.summary or "").replace("|", "/").replace("\n", " ")[:80]
        lines.append(f"| `{ep.command_name}` | {ep.method} | `{ep.path}` | {summary} |")
    if not endpoints:
        lines.append("| _(generic)_ | * | * | No spec endpoints; use raw HTTP via bash + curl |")
    lines += [
        "",
        "## Example",
        "",
        "```bash",
        f"python {cli_filename} --list",
        "```",
    ]
    return "\n".join(lines) + "\n"


def press(
    service: str,
    base_url: str = "",
    spec: dict | None = None,
    output_dir: str | Path = ".anvil/skills",
) -> PressResult:
    """Generate a CLI wrapper + skill for a service.

    Parameters
    ----------
    service:
        Human-readable service name (used for the skill name and env token).
    base_url:
        API base URL. Required if ``spec`` is not provided or lacks servers.
    spec:
        Optional OpenAPI/Swagger spec dict. If given, endpoints are extracted.
    output_dir:
        Directory under which a ``<service-slug>/`` skill folder is created.
    """
    slug = _slug(service).replace("_", "-")
    endpoints: list[Endpoint] = []
    if spec:
        spec_base, endpoints = parse_openapi(spec)
        base_url = base_url or spec_base
    if not base_url:
        raise ValueError("press: base_url is required when no spec servers are present")

    cli_filename = f"{_slug(service)}_cli.py"
    cli_source = generate_cli_source(service, base_url, endpoints, cli_filename)
    skill_md = generate_skill_md(service, base_url, endpoints, cli_filename)

    skill_dir = Path(output_dir) / slug
    skill_dir.mkdir(parents=True, exist_ok=True)
    cli_path = skill_dir / cli_filename
    skill_path = skill_dir / "SKILL.md"
    cli_path.write_text(cli_source, encoding="utf-8")
    skill_path.write_text(skill_md, encoding="utf-8")

    return PressResult(
        service=service,
        base_url=base_url,
        endpoints=endpoints,
        cli_path=cli_path,
        skill_path=skill_path,
        cli_source=cli_source,
        skill_md=skill_md,
    )
